version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls && whoami
      - ./mvnw clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 cp target/webgoat-2023.6-SNAPSHOT.jar s3://codebuild-test-hbucket/codebuildh/
      - aws s3 cp buildspec_owasp_zap.yml s3://codebuild-test-hbucket/codebuildh/
artifacts:
  files:
    - target/webgoat-2023.6-SNAPSHOT.jar
    - appspec.yml
    - start.sh
  name: WebGoatBuild-$(date +%Y-%m-%d)
