version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase…
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls && whoami
      - ./mvnw clean install
      - python3 zap_start.py
      - python3 zap_scan.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: none
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**
  discard-paths: yes
