version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    #commands:
    #  - pip3 install --upgrade git+https://github.com/Grunny/zap-cli.git
    #  - export PATH=$PATH:$HOME/.local/bin
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase…
  build:
    commands:
      - echo Build started on `date`
      - pwd && ls && whoami
      - ./mvnw clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: none
  files:
    - target/*.jar
    - appspec.yml
    - buildspec_zap.yml
    # zap_start.py
    # zap_scan.py
  #discard-paths: yes
