== Google Chrome Developer Tools

To complete certain assignments you sometimes may have to look at the JavaScript
source code or run a JavaScript command on your own.
To do that Google Chrome has a set of tools which allows you to do that and much much more.
While these tools are not specific to Google Chrome, almost every modern browser has a set
of their own, our introduction will focus on the ones found in Google Chrome.
You can however still use the browser of your choice, like Firefox or Safari, although some steps of this tutorial
may be different for you.

Keep in mind that the following tutorial, is not there to teach everything there is about these tools.
This tutorial will only focus on the essential knowledge you need to complete certain assignments.
Also if you are already familiar with these Tools you can safely skip these lessons.

To get started, *open the developer tools*. There are multiple ways to open them:

1. Right click anywhere in the browser window and select the option _"Inspect"_.
2. Go to the browser menu (three dots in the top right corner), then go to _"More tools"_ and select the option _"Developer tools"_.
3. Use the keyboard shortcut _Ctrl + Shift + I_