= Keystores 

A keystore is a place where you store keys.
 
== File based keystores 

A file based keystore is something that in the end has the keys on a file system.
Storing public certificates in a file based keystore is very common

== Database keystores

Keys and especially public certificates can of course also be stored in a database. 

== Hardware keystore

A hardware keystore is a system that has some sort of hardware which contain the actual keys.
This is typically done in high end security environments where the private key is really private.
In comparison with file based or database keystores, it is impossible to make a copy of the keystore to send it to some unknown and untrusted environment. 

Some certificate authorities that are used to provide you with a server certificate for your website, also create the private keys for you (as-a-service). However, it is by definition no longer considered a private key. For all keystore types, you should keep the private key private and use a certificate signing request to order your signing or server certificates.