=== Are your passwords secure?

What about you? Are your passwords secure?

There are dedicated websites that allow searching if one of your accounts got breached in a past data breach. +
Go to https://haveibeenpwned.com/Passwords[Have I Been Pwned] or https://www.dehashed.com/[DEHASHED] per example and test if your account got breached.
If so, better change your passwords *right now*!

==== What can you do to improve the security of your account?
- *use different passwords for different accounts* +
It is a good thing NOT to use the same password for multiple accounts but rather to use different passwords.
* *use passphrases* +
Use passphrase generators like https://www.rempe.us/diceware/#eff[Diceware] to generate passphrases.
Passphrases are passwords made out of several words instead of randomly generated character sequences.
This makes them way easier to remember for us human beings. And by the way: The longer, the better!
* *use a password manager* +
If you can't remember your different passwords, use a password manager to create and securely store your passwords.
- *use two-factor authentication* +
If possible, use two-factor authentication methods to add an extra layer of security to your accounts.
