== Qu'est-ce que WebGoat?
---

WebGoat est une application qui explique et teste diverses vulnérabilités du top 10 OWASP.

Il contient des leçons, des exercices et des défis (Challenges). Les leçons sont divisées en plusieurs catégories et contiennent des pages contenant des informations et des exercices. Vous devriez essayer les défis en dernier. Ceux-ci sont délicats et ne contiennent aucun indice.

Le but de WebGoat est d'apprendre et de tout expérimenter de manière ludique dans le domaine de la sécurité Web. Cela convient à la fois aux développeurs et aux testeurs.

N'hésitez pas à faire passer un test approfondi à WebGoat et à améliorer vos connaissances et votre expérience dans ce domaine.

Vous devriez essayer de résoudre les exercices d'application WebGoat avec un état d'esprit de piratage.

Merci pour ton intérêt!

*L'équipe WebGoat*

#La plupart des textes sont en anglais. Vous pouvez changer de langue via la liste déroulante du menu. Vous êtes également cordialement invité à traduire des textes pour améliorer WebGoat.#
