# Setup a Linux box headless which will start WebGoat and WebWolf helpful image to give away during training

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :forwarded_port, guest: 8080, host: 8080
  config.vm.network :forwarded_port, guest: 9090, host: 9090
  config.vm.provider "virtualbox" do |vb|
  	vb.gui = false
  	vb.memory = "4096"
  	vb.cpus = 2
  	vb.name = "WebGoat-Training"
	vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
  end
  config.vm.provider "vmware_fusion" do |vf|
    vf.gui = false
    vf.vmx["memsize"] = 4096
    vf.vmx["numvcpus"] = 2
    vf.vmx["displayname"] = "WebGoat-Training"
  end

  config.vm.provision "shell", inline: <<-SHELL
    wget https://github.com/WebGoat/WebGoat/releases/download/v8.0.0.M21/webgoat-server-8.0.0.M21.jar
    wget https://github.com/WebGoat/WebGoat/releases/download/v8.0.0.M21/webwolf-8.0.0.M21.jar
    sudo add-apt-repository ppa:openjdk-r/ppa
    sudo apt-get update
    sudo apt-get install openjdk-8-jre -y
    SHELL

  config.vm.provision "shell", run: "always", privileged: false, inline: <<-SHELL
    java -jar webgoat-server-8.0.0.M21.jar --server.address=0.0.0.0 &
    sleep 40s
    java -jar webwolf-8.0.0.M21.jar --server.address=0.0.0.0 &
    SHELL

end
