== JWT signing

Each JWT token should be signed before sending it to a client, if a token is not signed the client
would be able to change the contents of the token. The signing specifications are defined
https://tools.ietf.org/html/rfc7515[here], and
the specific signing algorithms you can use are described https://tools.ietf.org/html/rfc7518[here] (_You will need to read
about this for the assignment_).

In practice, signing a JWT typically involves either:

- HMAC with SHA‑2 _(symmetric key)_
- Digital signatures using RSASSA‑PKCS1‑v1_5, ECDSA, or RSASSA‑PSS _(asymmetric keys)_

These algorithms ensure the token’s integrity and allow the server to verify that the token has not been tampered with.

=== Checking the signature

One important step is to *verify the signature* before performing any other action, as we wouldn't want to use a token
that has been tampered with.

== Assignment

Try to change the token you receive and become an admin user. Once you are an admin, reset the votes.
