=== More About Logging

There are a few more topics we might want to cover here:

- How to work with log-levels
- How to do Exception Handling
- How to use logging for other purposes
- Some resources to read up on.

==== Log Levels
Explain log levels

==== Exception Handling
 exception handling (maybe an example of logging exception towards the client with cryptography and why this is a bad idea)


==== Audit Logging, Security Event Monitoring, and Application Logs
Note that logging is often used for more than just application debugging. Application logs are often used as a feed for other purposes, think of:

 - Audit logging: here specific events need to be recorded by your application log in order to recreate the order of events that were TODO: CONTINUE HERE!
 - Security Event Monitoring
 - Fraud Detection
 - GDPR requests for information
 - Compliance monitoring
 - Business process monitoring
 - ...etc.

==== More reading

- The OWASP Logging Cheat sheet: https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html
- TBD