name: CI-Coverity-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch: 
  
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Coverity Scan
        uses: synopsys-sig/synopsys-action@v1.11.0
        with:
          ### SCANNING: Required fields
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          
          ### Coverity Connect users - Uncomment below
          coverity_local: true
        
          ### POLICY ENFORCEMENT: Uncomment to break build on policy
          coverity_policy_view: 'Outstanding Issues' 
        
          ### PULL REQUEST COMMENTS: Uncomment below to enable
          coverity_prComment_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled  
