== What is SQL

SQL is a standardized (ANSI in 1986, ISO in 1987) programming language which is used for managing relational databases and performing various operations on the data in them.

A database is a collection of data. Data is organized into rows, columns and tables, and it is indexed to make it easier to find relevant information.

Example SQL table with employees:

Employees Table
|===
|IdNum |LName |FName |JobCode |Salary |Phone |

|1876 |CHIN |JACK |TA1 |42400 |212/558-5634 |

|1114 |GREENWALD |JANICE |ME3 |38000 |212/558-1092 |

|1556 |PENNINGTION|MICHAEL |ME1 |29860 |718/383-5681 |

|1354 |PARKER |MARY |FA3 |65800 |914/455-2337 |

|1130 |WOOD |DEBORAH |PT2 |36514 |212/587-0013 |
|===

Each employee has an index (IdNum), lastname, firstname, job title (JobCode), salary and a phone number. All his data from this table is represented in a single row.

By using SQL queries you can modify a database table and its index structures, add, update and delete rows of data.

There are three types of SQL commands in the SQL database language:

If you are still struggling with SQL and need more information or practice you can visit http://www.sqlcourse.com/ for an interactive and free online training.
